version: "3.8"

services:
  fastapi-service:
    build: .
    container_name: fastapi
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - TZ=UTC
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SERPER_API_KEY=${SERPER_API_KEY}
      - PROXY_URL=${PROXY_URL}
    volumes:
      - ./logs:/app/logs